import Image from 'next/image'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'
import Footer from '../components/Footer'
import About from '@/components/About'
import Testimonial from '@/components/Testimonial'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    <Head>
        <title>WriteUp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <Navbar />
      <Hero heading='Welcome to WriteUp: A Haven for Text-Based Content'  message='Unleash the Power of Words, Connect with Like-minded Readers and Writers' />
      <About />
      <Testimonial />
      <Footer />
    </>
  )
}
